# Generated by Django 3.1.13 on 2021-09-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20210904_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_id',
            new_name='session_number',
        ),
    ]
