# Generated by Django 3.1.13 on 2021-08-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20210826_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.TextField(blank=True, max_length=16, null=True),
        ),
    ]
