# Generated by Django 3.1.13 on 2021-08-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_order_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
    ]
