# Generated by Django 3.1.13 on 2021-08-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='prueba a cambiar'),
            preserve_default=False,
        ),
    ]
