# Generated by Django 3.1.13 on 2021-08-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_auto_20210830_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
