# Generated by Django 3.1.13 on 2021-08-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_auto_20210816_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_Date',
            new_name='ordered_date',
        ),
    ]
