# Generated by Django 3.1.13 on 2021-08-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=10000),
            preserve_default=False,
        ),
    ]
